<a href="https://colab.research.google.com/github/boscochanam/pythonprac/blob/master/Learning_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.3.1+cu121


In [3]:
TENSOR = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
TENSOR

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
TENSOR.ndim

2

## Random Tensors

In [6]:
random_tensor = torch.rand(2,3,4)

In [7]:
random_tensor

tensor([[[0.5060, 0.3665, 0.7150, 0.0582],
         [0.6976, 0.4494, 0.7398, 0.1570],
         [0.2134, 0.7814, 0.4825, 0.4646]],

        [[0.2246, 0.3119, 0.3782, 0.0753],
         [0.6799, 0.4313, 0.3247, 0.6458],
         [0.0810, 0.6893, 0.8187, 0.6344]]])

In [8]:
random_image_size_tensor = torch.rand(size=(224,224,3))

In [9]:
random_image_size_tensor

tensor([[[3.6196e-02, 8.4883e-01, 5.1776e-01],
         [2.6835e-01, 8.2708e-01, 6.5361e-01],
         [1.0567e-01, 7.5634e-01, 5.7762e-01],
         ...,
         [1.1929e-02, 4.1036e-01, 4.9724e-01],
         [3.8842e-01, 6.0260e-01, 7.2990e-01],
         [6.6006e-01, 5.9624e-01, 8.9356e-01]],

        [[7.5528e-01, 8.2888e-01, 7.9001e-01],
         [9.9248e-01, 1.6705e-01, 7.1032e-01],
         [6.1441e-01, 5.0593e-01, 6.8122e-01],
         ...,
         [8.4839e-01, 2.4937e-01, 9.0461e-01],
         [5.1154e-01, 8.8458e-01, 3.9277e-01],
         [5.0212e-01, 9.4657e-01, 5.7330e-01]],

        [[2.4902e-01, 6.2596e-01, 1.7398e-01],
         [4.6489e-01, 8.4636e-02, 2.4990e-01],
         [3.2661e-01, 6.8837e-01, 7.5952e-01],
         ...,
         [1.6763e-01, 9.6726e-01, 4.0490e-02],
         [1.4456e-01, 2.0390e-01, 2.8021e-02],
         [6.0713e-04, 2.4208e-01, 3.0683e-01]],

        ...,

        [[6.5350e-01, 2.3102e-01, 7.6838e-01],
         [3.7505e-01, 4.1558e-01, 5.1171e-02]

In [10]:
ones = torch.ones(size = (3,4))

In [11]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
one_to_ten = torch.arange(start=0,end=5)

In [13]:
one_to_ten

tensor([0, 1, 2, 3, 4])

In [14]:
ten_zeroes = torch.zeros_like(input=one_to_ten)

In [15]:
ten_zeroes

tensor([0, 0, 0, 0, 0])

# Tensor DataTypes

In [16]:
float_32_tensor = torch.tensor([[[3,1],[3,2]]],dtype=torch.float32)

In [17]:
float_32_tensor

tensor([[[3., 1.],
         [3., 2.]]])

In [18]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [19]:
float_result = float_16_tensor * float_32_tensor
float_result.dtype

torch.float32

In [20]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.T

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
print(ones.transpose)

<built-in method transpose of Tensor object at 0x7a48d4fc0540>


In [23]:
# Create a tensor of shape (2, 3, 4)
tensor = torch.arange(24).reshape(2, 3, 4)
print("Original tensor shape:", tensor.shape)
print("Original tensor:\n", tensor)

# Permute the tensor dimensions
permuted_tensor = tensor.permute(1, 0, 2)
print("\nPermuted tensor shape:", permuted_tensor.shape)
print("Permuted tensor:\n", permuted_tensor)

# Reshape the tensor
reshaped_tensor = tensor.reshape(3, 8)
print("\nReshaped tensor shape:", reshaped_tensor.shape)
print("Reshaped tensor:\n", reshaped_tensor)

Original tensor shape: torch.Size([2, 3, 4])
Original tensor:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

Permuted tensor shape: torch.Size([3, 2, 4])
Permuted tensor:
 tensor([[[ 0,  1,  2,  3],
         [12, 13, 14, 15]],

        [[ 4,  5,  6,  7],
         [16, 17, 18, 19]],

        [[ 8,  9, 10, 11],
         [20, 21, 22, 23]]])

Reshaped tensor shape: torch.Size([3, 8])
Reshaped tensor:
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])


In [24]:
# Create *known* parameters
weight = 0.7
bias = 0.3

# Create data
start = 0
end = 1
step = 0.02
X = torch.arange(start, end, step).unsqueeze(dim=1)
y = weight * X + bias

X[:10], y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

## Training Linear Regression Model

In [25]:
X = torch.rand(size=(5,1))
m = 0.3
c = 0.2
y = m * X + c

In [26]:
print(X)
print(y)

tensor([[0.6551],
        [0.0964],
        [0.0564],
        [0.9472],
        [0.6780]])
tensor([[0.3965],
        [0.2289],
        [0.2169],
        [0.4842],
        [0.4034]])


In [ ]:
from torch import nn

class LinearRegressionModel(nn.Module):